apiVersion: 1

datasources:
  - name: PostgreSQL INMET
    uid: PostgreSQL INMET
    type: postgres
    access: proxy
    url: postgres:5432
    user: inmet_user
    secureJsonData:
      password: inmet_password
    jsonData:
      database: inmet_db
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true


